Infected
ct-fiuba/ct-virus-tracker pull request #1
Opened 2021-01-09 23:27 UTC by olifer97

Agrego estructura basica del server

Agrego endpoint para registrar visitas como infectadas POST /infected donde recibe un array de visitas a marcar como infectadas

@ct-fiuba/developers

2021-01-10 00:53 UTC, olifer97 commented on src/models/schemas/Visit.js
> +let visitSchema = mongoose.Schema({
No estoy segura si es necesario poner en el schema de acamel scanCode, isExit y el timestamp

2021-01-10 15:06 UTC, tomasaccini requested changes
Tremendo laburoooo oli! dejo un par de comentarios sobre:
- cambios de puerto que ya estaba usado
- lo del schema de visits
- pregunta sobre qué parametros son necesarios para recibir en el endpoint

2021-01-10 15:06 UTC, tomasaccini commented on .env.development
> +PORT=5005
Le podemos cambiar el port? el visit-manager también usa el 5005. El 5007 no lo esta usando nadie por ejemplo

```suggestion
PORT=5007
```

2021-01-10 15:06 UTC, tomasaccini commented on Dockerfile.web
> +EXPOSE 5005
```suggestion
EXPOSE 5007
```

2021-01-10 15:06 UTC, tomasaccini commented on Makefile
> +	curl -vvv "localhost:5005/ping"
```suggestion
	curl -vvv "localhost:5007/ping"
```

2021-01-10 15:06 UTC, tomasaccini commented on test/integration/app.int.test.js
> +  server = await app.listen(5005);
```suggestion
  server = await app.listen(5007);
```

2021-01-10 15:06 UTC, tomasaccini commented on src/controllers/infectedController.js
> +        return res.status(404).json({ reason: `${visits.length - count.n} visits not found` });
Se podrá agregar info tipo cuales fueron los códigos que encontró y cuales no? No es 100% necesario igual, pero digo xq incluso si tira un error 404 puede haber códigos que se updatearon

2021-01-10 15:06 UTC, tomasaccini commented on src/models/schemas/Visit.js
> +let visitSchema = mongoose.Schema({
Mmm funciona todo bien si ponemos solo los parámetros que se usan en este servicio no? No se bien que se suele hacer en estos casos, pero si usamos todos los parámetros se terminan acoplando más los servicios y si después se agrega algo en el visit-manager que no se usa acá deberíamos mantener la consistencia. no se si hay alguna solución más elegante, @NachoRaik.

2021-01-10 15:06 UTC, tomasaccini commented on src/static/swagger.json
> +          }
En este endpoint necesitamos recibir el scanCode y el timestamp? segun entiendo solo con recibir los userGeneratedCode funcionaría xq no veo que se usen en otro lado

2021-01-10 15:06 UTC, tomasaccini commented on test/integration/app.int.test.js
> +        await request(server).post('/infected').send({ visits: [visit1, visit2] }).then(res => {
Idem acá, podría recibir de una lista de userGeneratedCodes en vez de las visitas completas?

2021-01-10 15:06 UTC, tomasaccini commented on src/middlewares/bodyValidatorMiddleware.js
> +    body(['visits.*.userGeneratedCode'], "Visit must have userGeneratedCode").not().isEmpty(),
Acá parecería que lo único que se necesita es el userGeneratedCode, y no toda la info de visits

2021-01-10 20:16 UTC, olifer97 commented on src/models/schemas/Visit.js
> +let visitSchema = mongoose.Schema({
Si, me parece que no ser relacional no hay problema de consistencia, no chequea eso y como solo agrega un campo el endpoint podria solo poner el userGeneratedCode que es el que se usa como indice

2021-01-10 20:22 UTC, olifer97 commented on .env.development
> +PORT=5005
Dale lo agrego, igual en el repo general lo puse en el 5007 pero como aca es para correrlo individual le deje el mismo. Igual lo cambio

2021-01-10 20:23 UTC, olifer97 commented on src/controllers/infectedController.js
> +        return res.status(404).json({ reason: `${visits.length - count.n} visits not found` });
Mmmm no estoy segura que me tire esa info si uso updateMany, solo me tira la cantidad que logro modificar, sino puedo updatear de a uno por vez para que sean distinguibles. De todas formas nose si para el celular es relevante, podria en caso de que alguno fallo seguir enviadolos todos.

2021-01-11 12:45 UTC, tomasaccini approved these changes
Magiccc

2021-01-15 19:35 UTC, NachoRaik commented on src/models/schemas/Visit.js
> +let visitSchema = mongoose.Schema({
Si pueden mismatchear, genial, banco dejarlo asi entonces.

2021-01-15 19:36 UTC, NachoRaik commented on src/models/schemas/Visit.js
> +let visitSchema = mongoose.Schema({
No falta el ID del lugar?

2021-01-15 19:43 UTC, NachoRaik approved these changes
Belisimo

2021-01-15 19:43 UTC, NachoRaik commented on test/integration/app.int.test.js
> +        await request(server).post('/infected').send({ visits: [visistNotSaved] }).then(res => {
```suggestion
        await request(server).post('/infected').send({ visits: [visitsNotSaved] }).then(res => {
```

2021-01-15 19:43 UTC, NachoRaik commented on test/integration/app.int.test.js
> +      test('should return 400 when visit not found', async () => {
Dice 400 pero se devuelve 404. Creo que lo correcto seria 404, no?

2021-01-15 19:43 UTC, NachoRaik commented on test/integration/app.int.test.js
> +      test('should return 400 when visit not found', async () => {
Igual no entendi. Si lo que esta ocurriendo es un POST, como puede dar 404?

2021-01-16 12:19 UTC, olifer97 commented on test/integration/app.int.test.js
> +      test('should return 400 when visit not found', async () => {
esq es un POST con info que tiene que existir en el sistema, si no existe se avisa que no se encontro o no?

2021-01-16 12:59 UTC, olifer97 commented on src/models/schemas/Visit.js
> +let visitSchema = mongoose.Schema({
Para que el ID del lugar?

2021-01-29 17:30 UTC, merged